### ISSUE TITLE
Vignette missing key bits of code

### ISSUE THREAD

**Issue by DataKritter** [StatsGary/OddsPlotty#1]
Thank you for such a great package :)
In the vignette, in the "Training the GLM using Caret" section, the glm_model code shows, but then immediately under it, it says "Once the model is trained, we can inspect the results with OddsPlotty", but then no code shows, so I can't see HOW to inspect the results with OddsPlotty myself.  Perhaps the code block is set to echo = FALSE?

**Comment by StatsGary** [comment]
This has now been resolved. Thanks for bringing this to my attention.
