### ISSUE TITLE
How to sort odds_plot by name?

### ISSUE THREAD

**Issue by styeretzian** [StatsGary/OddsPlotty#3]
I am trying to visualize logistic regression and I find OddsPlotty extremely useful. I would like to know if there is any way to sort data not by Odds ratio (high to low/right to left) but by name (e.g. so that age groups or income levels are sorted back to back). 
And is there any way to change the fonts in the plot?

Please let me know!
Thanks

**Comment by StatsGary** [comment]
You can change fonts like any other ggplot2 object: https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2#:~:text=To%20change%20all%20the%20fonts,sans and to reorder you would need to use the forcats package.
